### ISSUE TITLE
sidebar menu button

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#1]
It shouldn't slide to the left, but keep the word "menu" in its exact same place, only changing the icon from three horizontal lines to a "x" (meaning close menu):
![screen shot 2015-01-05 at 22 39 13](https://cloud.githubusercontent.com/assets/10408369/5620381/bdbd8b20-952b-11e4-899b-d65ee9c31d87.png)
![screen shot 2015-01-05 at 22 39 20](https://cloud.githubusercontent.com/assets/10408369/5620382/bdc0ac38-952b-11e4-9724-3b2fdae8e81b.png)

**Comment by esperancaJS** [comment]
what happens to the blank space where 'menu' used to be ? disappears with a transition ?

**Comment by mariacovasgrilo** [comment]
https://tictail.com/ see the menu button on the upper rightish side? The whole page changes but that sucker stays exactly in the same place, the only thing that changes is the icon. I'm pretty sure I saw this animation's code somewhere. I will drop it here as soon as I find it.

**Comment by mariacovasgrilo** [comment]
http://tympanus.net/codrops/2013/11/05/animated-svg-icons-with-snap-svg/

view the demo and on the upper right corner there it is, the proper animation. Now I don't know if the icon has the right size but I think I will manage to either find a more adequate one or to make our own.

It's just that right now it has like the perfect proportion relatively to the "menu" type you see?

**Comment by esperancaJS** [comment]
but you didn't understand my question.. 
so the buttons on the bar just stay completely in the same position (they are removed from the bar)?

**Comment by mariacovasgrilo** [comment]
theoretically they are not on the bar, they are over the bar, with the sidebar sliding over the horizontal bar and beneath the buttons. so yeah, the space on the horizontal bar where it used to have the buttons will now be empty. If I still didn't answer this right try using pictures to help me understand what you are talking about.
