### ISSUE TITLE
zoom in pictures kinda cluttered

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#10]
I think this is a better solution: http://www.asos.com/ASOS/ASOS-Reclaimed-Vintage-Dress-With-Embroidery/Prod/pgeproduct.aspx?iid=4908575&cid=8799&sh=0&pge=0&pgesize=36&sort=-1&clr=White&totalstyles=1968&gridsize=3

(click on the image to see the zooming system)

Basically 1) it removes the white borders 2) allows for very close zoom, to actually see the details of the product 3) has the little side thumbnails which are cool to navigate, better than the arrows

I would even darken the background and remove the "close" button, it's redundant since you can just click outside the popup to close. The arrows can also be removed and just use the thumbnails to navigate, or even depending on the area of the image you click you go right or left, like on facebook.

All the other stuff like price, buying and sharing options (etc) can be totally removed from the zooming situation since that is the kind of stuff people do on zoom out. The zoom is for inspecting, seeing, ok I like it, back, buy.

**Comment by esperancaJS** [comment]
you are totally right!
For now I made the zoomed image occupy the whole modal/popup since it's fast
I'll implement the thumbnails, remove the arrows and handle the mouse/image position soon ;)

**Comment by esperancaJS** [comment]
I feel like we could leave this feature as is.. without thumbnails.
At least until we have everything else we need to launch.
Agree ?

**Comment by mariacovasgrilo** [comment]
Yeah I don't think the thumbnails are urgent or anything. But I will soon add here a good substitute for those arrows, I find them too overwhelming. So don't close this just yet!

**Comment by mariacovasgrilo** [comment]
how about this one? http://iconmonstr.com/arrow-25-icon/

**Comment by esperancaJS** [comment]
They look good, did you see that issue I opened about the icons? 
Start downloading all the icons you want us to use ;)

**Comment by mariacovasgrilo** [comment]
Yes I saw that issue and I don't feel like those ones fit our look because they have round edges. I tried them and I didn't really like the result. But yeah, soon enough I will export aaaall the icons we are using.

**Comment by djtanuzzo** [comment]
How is this one ready for review? Nothing has changed and item pictures are still a mess.

**Comment by esperancaJS** [comment]
in what way ?

**Comment by djtanuzzo** [comment]
1 - The preview image before opening the item is cropped.
2 - Item images are cropped.
3 - There is no way to see how many images the item has.
4 - There is no preview of what images the item has.
5 - When you zoom on the images they are cropped.
6 - When you zoom on the images you can't move them or re-size them to see more.

**Comment by esperancaJS** [comment]
![focal point](https://cloud.githubusercontent.com/assets/1115163/7238441/3118e5a2-e7ab-11e4-93be-b97510d5d02a.png)

squarespace introduced(as far as I know) a concept called focal point, I think it's more dynamic than cropping (not that one replaces the other)

**Comment by mariacovasgrilo** [comment]
Buggy situation over here:
![screen shot 2015-04-26 at 23 01 23](https://cloud.githubusercontent.com/assets/10408369/7339467/3180a9a0-ec68-11e4-8680-fe9f2ed3687b.png)
![screen shot 2015-04-26 at 23 01 28](https://cloud.githubusercontent.com/assets/10408369/7339468/32a48f22-ec68-11e4-9cbd-d89791b33189.png)

I also don't know about the animation being used, but it's definitely not a deal breaker. So after this bug being solved, I'd close it!

Note: once the clusterfuck of problem solving is done, I will create an issue just documenting intended animations for ux/ui purposes, since I think they will be game changing in general.
