### ISSUE TITLE
Item images with opacity clip over each other

### ISSUE THREAD

**Issue by djtanuzzo** [merkatsu/website#100]
When going through the images of an item which have opacity they clip over each other, making for a weird and annoying unintended effect.

![mrkts10](https://cloud.githubusercontent.com/assets/10848233/7234616/38451470-e780-11e4-9506-fa8db4d8a91e.png)

**Comment by esperancaJS** [comment]
@mariacovasgrilo should I give the images a default white background to counter this? Or any other idea ?

**Comment by djtanuzzo** [comment]
This issue is still persisting, even with the new image previews. I think that you should give the images a default white background to counter this.
