### ISSUE TITLE
When to display store covers, collection covers, page covers

### ISSUE THREAD

**Issue by djtanuzzo** [merkatsu/website#105]
We had been talking about when should store covers, collection covers and page covers be displayed. We are divided on how to proceed, so feedback is welcome. This started with the following issue:

In the current system if the user has a store cover, and all of his collections have covers, and all of this pages have covers, and one of his collections is his home page, then the store cover is never shown.

We then came up with several ways this could be approached:
1) The store cover is displayed on the collection/page that is set as the home page, and on all collections and pages that don't have a cover.
2) The store cover is removed as an option. Only collection and page covers remain.
3) The collection and page covers are removed as an option. Only the store cover remains.

**Comment by djtanuzzo** [comment]
IMO we should go with approach nr.3, for the following reasons:
- The problem with approach nr.1 is that it could cause confusion for the user. He may not understand why the collection he set as his homepage now suddenly doesn't use its own cover any more.
- The problem with approach nr.2, and generally with having collection/page covers, is that the store loses its identity, and its easier for users to get lost. Since everyone has the same looking stores, there are only a few factors that differentiate one store from the other: the name, the logo and the cover. If the covers constantly change depending on what collection/page the user is in, it becomes increasingly difficult for users to identify where they are at a glance.
- This is why I opt for approach nr.3, the removal of collection/page covers. By having each store use its store cover on all collections and pages, we keep the branding consistent and help users navigate through the platform. We would also be simplifying the user experience and store creation, having one less barrier of entry to the platform.

**Comment by esperancaJS** [comment]
Can't shake of that option 3 is included in option 1.
And option 1 allows for deeper customization, some lists and pages could benefit from having their own 'personality' allowing a market or store to differentiate it's lists and pages.

But yes.. 1 leads to great confusion right now.. Really want to find a way where it becomes obvious

**Comment by esperancaJS** [comment]
the biggest problem with 1 right now:
 it's impossible to edit the store cover if the store home has a cover of it's own

**Comment by esperancaJS** [comment]
crazy possible solution for approach 1:
- check box: `always show on home`
- when the mouse is over the default cover editor the default cover will show always, if it's not on home or if the above checkbox is not checked it will go back to the correct cover as soon as the mouse leaves the cover

**Comment by esperancaJS** [comment]
another possible solution for approach 1:
- when the mouse is over the main cover editor the main cover will show always, replacing the current cover if needed (as in the previous comment)
- editor descriptions on:
  - main: "main cover appears on the home page and on collections and pages that don't have their own cover.
  - collection and page: "this cover replaces the main cover except on the homepage"

**Comment by esperancaJS** [comment]
oh wait.. by making the home always have the default cover this becomes easier.

for editing the main cover: edit in home page
for editing the list/page covers: edit it it their respective pages

which is basically the initial way this worked, now I don't understand why I was so confused :p
