### ISSUE TITLE
Where and how to display call to action buttons on "main" page ?

### ISSUE THREAD

**Issue by esperancaJS** [merkatsu/website#106]
As suggested on #86:
So side pages should automatically open from buttons.

Examples:
- edit market/store/page/item/collection
- add items to collection/market

**Comment by mariacovasgrilo** [comment]
I think the solution lies on some sort of hovering system that then changes for mobile to just showing a pencil in a circle icon when you are in the page of the editable thing. 

For the cases of adding items I also think the solution should be similar, in both cases having the icon standing as close as possible to the title of the thing to be edited or added to.

In any case I will be working on this icon and posting design updates here.

**Comment by esperancaJS** [comment]
I was thinking that a potential way to differentiate markets from store (since this is still not solved) would be for markets to have a button next to the title saying like `post items`. 
But this kind of button should be always visible.

Also even though I like the idea of showing only on hover since it makes the layouts a million times cleaner it might not be intuitive in this case.
Other cases where we show stuff only on hover is in editors which is something that the user will naturally hover, a name maybe he will not remember to hover

**Comment by mariacovasgrilo** [comment]
Yes, it's true. In those cases I will probably have it visible at all times, in the best way possible.

**Comment by esperancaJS** [comment]
this is very important for issue #120

**Comment by mariacovasgrilo** [comment]
There's a solution for the item pop ups on #109
