### ISSUE TITLE
Shadow

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#11]
![screen shot 2015-01-21 at 15 12 00](https://cloud.githubusercontent.com/assets/10408369/5838196/ea06480a-a185-11e4-944d-09d487d5a2f1.png)

So basically once I saw more and more into the material design thing, turned out that a subtle fading shadow is better than a solid one, it creates less visual clutter whilst it definitely makes the popup stand out.

![image](https://cloud.githubusercontent.com/assets/10408369/5838167/a750ecb8-a185-11e4-927e-9af1367ae2ab.png)

As you can see in this picture, there's then different blurs of shadow depending on how "ahead" of the other sheets it is, but that is something we can then go on more detail. I think for now you could easily use more or less the same measurement of the first shadow on the left.

**Comment by esperancaJS** [comment]
I worked a bit on trying to differentiate the shadows, but yes, they might still need some work

**Comment by PedroEsperanca** [comment]
I worked a bit on trying to differentiate the shadows, but yes, they might still need some work
