### ISSUE TITLE
Open preview of cart when "add to cart" is clicked

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#111]
Having the cart preview briefly opening would be a clear sign that the item was added to the cart (like on this site: http://www.zara.com/pt/pt/mulher/jeans/ver-tudo/cal%C3%A7as-de-ganga-boyfriend-com-rasg%C3%B5es-c719019p2638061.html )

In which case this message would be redundant 
![screen shot 2015-04-26 at 22 27 07](https://cloud.githubusercontent.com/assets/10408369/7339499/d06c1130-ec68-11e4-8932-8ab62cb062ac.png)

The layout for this element of the page is on issue #37

**Comment by esperancaJS** [comment]
I implemented a solution (feel free to try it) that solves this lack of communication and also allows for adding the same item multiple times with different item options.

after clicking on item name (in cart) or opening an item that is already in cart in a list:
![image](https://cloud.githubusercontent.com/assets/1115163/7490081/f879eb00-f3e5-11e4-9671-2442490014e9.png)

after clicking edit (in cart or here in the item popup):
![image](https://cloud.githubusercontent.com/assets/1115163/7490151/915c7cca-f3e6-11e4-8735-85da00a246ca.png)

**Comment by mariacovasgrilo** [comment]
I think for now it's working good, I would just put the list of the items in the cart under the "add more", and I would also add the other items that I already have in the cart to the list, even if they are not the same item.
