### ISSUE TITLE
perfect bar and bar buttons for mobile

### ISSUE THREAD

**Issue by esperancaJS** [merkatsu/website#118]

**Comment by mariacovasgrilo** [comment]
TOP BAR

![shop mobile](https://cloud.githubusercontent.com/assets/10408369/7428813/f6d75cf6-efee-11e4-81e1-54169f94f2d3.png)

/\* CART "2": */
font-family: Montserrat-Regular;
font-size: 18px;
color: #E53527;

/\* FUKKBOYS AND PEOPLE : */
font-family: Montserrat-Light;
font-size: 14px;
color: #302B2F;
letter-spacing: 0.87px;
line-height: 18px;
margin-bottom: 20px;

/\* Simples Loja: */
font-family: Montserrat-Hairline;
font-size: 36px;
color: #302B2F;
line-height: 43px;
margin-left: 20px;
margin-top: 30px;

header height: 127px
menu icon margin right: 30px
banner image height: 300px

**Comment by mariacovasgrilo** [comment]
SHOP MENU SIDEBAR

![shop mobile menu shop](https://cloud.githubusercontent.com/assets/10408369/7429958/25834056-f003-11e4-9e3f-a5820781d158.png)

sidebar width: 280px;
accessories, clothing, shoes margin-left: 20px;
accessories margin-top: 46px;
distance between dividing lines: 93px;

/\* Lines: */
border: 1px solid #3D363B;

/\* USER, ACCESSORIES, CLOTHING...: */
font-family: Montserrat-Light;
font-size: 20px;
color: #FFFFFF;
letter-spacing: 1.3px;

/\* SHOP: */
font-family: Montserrat-Light;
font-size: 20px;
color: #E53527;
letter-spacing: 1.3px;

as a reference for the alignments of the tabs:
![screen shot 2015-05-01 at 13 14 37](https://cloud.githubusercontent.com/assets/10408369/7430002/158b7b72-f004-11e4-861c-5494e036fe5f.png)

/\* Tab Marker: */
background: #E53527;
width: 140px;
height: 3px;

/\* Top section that includes cart, close button and tabs: */
background: #201D20;
box-shadow: 0px 3px 5px 0px rgba(0,0,0,0.25);

**Comment by mariacovasgrilo** [comment]
![shop mobile menu user](https://cloud.githubusercontent.com/assets/10408369/7430078/71c984d2-f005-11e4-89b9-6f6d2da9aa60.png)

/\* Rectangle 72: */
background: #E53527;
box-shadow: 0px 4px 4px 0px rgba(0,0,0,0.35);
border-radius: 2px;
width: 220px;
height: 52px;

/\* KNOW MORE & LOGIN: */
font-family: Montserrat-Light;
font-size: 20px;
color: #FFFFFF;
letter-spacing: 1.38px;
line-height: 18px;

/\* Please log in or reg; Know all about our s: */
font-family: Montserrat-Hairline;
font-size: 20px;
color: #FFFFFF;
line-height: 25px;

/\* logo: */
width: 166px;
margin-bottom: 35px;

**Comment by mariacovasgrilo** [comment]
![shop mobile menu user copy](https://cloud.githubusercontent.com/assets/10408369/7430114/e3051814-f005-11e4-91cc-097477ba7c68.png)

distance between "username" and the tab is the same as the shop menu.
distance between lines is the same as in the shop menu.
length of shorter lines is 200px;
margin left of submenu elements (cart, client orders, etc..): 40px;

**Comment by mariacovasgrilo** [comment]
The idea is that then, when the user clicks on any of the sidebar menus like "cart" or "client orders" or whatever, the sidebar goes full width and has roughly the same layout as on desktop. I still have to test its mobile friendliness.
