### ISSUE TITLE
buttons with caps lock and round 1px radius corners

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#12]
Like here:
![screen shot 2015-01-21 at 16 28 36](https://cloud.githubusercontent.com/assets/10408369/5838884/a643de02-a18a-11e4-8e39-f80318a2856c.png)

"buy", "share" , "comments" should be in caps lock too.

**Comment by esperancaJS** [comment]
I tinkered a bit with font sizes and weights also so the attributes are there, feel free to play with the values ;)
