### ISSUE TITLE
Item images should "fit to screen"

### ISSUE THREAD

**Issue by djtanuzzo** [merkatsu/website#129]
One of the more confusing aspects of the current item images is that there is no way to see them fully because they are always zoomed in in some way. This means that the user cannot get a full picture of what the actual item image looks, which makes for a pretty bad experience.

The way it should work is that when you click on the image you see the full image, basically making it "fit to screen". This is a standard behavior used by pretty much all shops and other sites on the internet.

![mrkts9](https://cloud.githubusercontent.com/assets/10848233/8253609/69959ae4-1689-11e5-8591-b35178b77961.png)

 If you want to see it in action right-click on any large image in your browser and select "open image in new tab". The image will fit to screen and you can then zoom in if you like.

**Comment by esperancaJS** [comment]
closing because use of the word "should"
