### ISSUE TITLE
sidebar space

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#13]
I am feeling very claustrophobic with the spacing here:

![screen shot 2015-01-22 at 11 49 30](https://cloud.githubusercontent.com/assets/10408369/5854317/d8bcd878-a22c-11e4-92dd-6e35e33887c7.png)
![screen shot 2015-01-22 at 11 50 39](https://cloud.githubusercontent.com/assets/10408369/5854326/ea57b9cc-a22c-11e4-9eb8-16b88c3621bd.png)

Let's give it a nice side spacing of 30 px (at least) left and right.

**Comment by esperancaJS** [comment]
I will have to increase the width then, is that ok ? (or reduce font sizes)

**Comment by mariacovasgrilo** [comment]
of course, increase the width, don't reduce the fonts. The sidebar is still pretty thin, actually too thin in my opinion.

**Comment by esperancaJS** [comment]
I wasn't sure if the border lines should extend to the ends or not so I made them shorter
