### ISSUE TITLE
checkbox layout

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#14]
So this is the current state of the checkboxes:

![screen shot 2015-01-23 at 10 02 25](https://cloud.githubusercontent.com/assets/10408369/5872062/00d84ed6-a2e7-11e4-8ad3-0230d6c73e47.png)

I'd say let's go for this, with no tilting animation on hover, it's kinda overwhelming visually. When you hover, the outline box can become the highlight color.
![screen shot 2015-01-23 at 09 51 14](https://cloud.githubusercontent.com/assets/10408369/5872102/865a5ae0-a2e7-11e4-9ec7-89e91fdb94c3.png)

Another detail is the shape of the checkboxes themselves which should only have a corner radius of 1px.

**Comment by esperancaJS** [comment]
corrected ;)
