### ISSUE TITLE
sidebar lines -> full width

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#15]
What happens is that if those divisive lines don't have the sidebar's full width, they get confused with text lines, and create more visual noise instead of separating the different sections.

![screen shot 2015-01-25 at 19 49 19](https://cloud.githubusercontent.com/assets/10408369/5892777/5f31e448-a4cb-11e4-9786-39fade9b766c.png)

**Comment by esperancaJS** [comment]
yep, I agree
