### ISSUE TITLE
exit and save buttons

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#16]
So I was tweaking on some stuff that was bothering me and I came to a realization in what comes to these buttons:
![screen shot 2015-01-27 at 11 57 04](https://cloud.githubusercontent.com/assets/10408369/5917316/a3ba7f84-a61b-11e4-9572-c813a7d47a36.png)

As you can see (or maybe not, because it's not that obvious come to think about it) I made some changes. The active button (in this case "exit") has a slight shadow and the unactiveness of the "save" button is now more properly visible.

here are the css attributes: 
/\* Rectangle 72: _/
background: #302B2F;
border-radius: 2px;
/_ SAVE: */
font-family: Montserrat-Regular;
font-size: 14px;
color: #767075;
line-height: 18px;

/\* Rectangle 72: _/
background: #E53527;
box-shadow: 0px 2px 2px 0px rgba(0,0,0,0.24);
border-radius: 2px;
/_ EXIT: */
font-family: Montserrat-Regular;
font-size: 14px;
color: #201D20;
line-height: 18px;

/\* EDIT LISTS: */
font-family: Montserrat-Bold;
font-size: 14px;
color: #FFFFFF;
letter-spacing: 0.88px;
line-height: 18px;

You might want to pay attention also to the "edit lists" attributes since they are used across the platform plenty of times.

**Comment by mariacovasgrilo** [comment]
I forgot to say that these are basically attributes for "normal" and "disabled", of course that once a user makes changes, the "save" button has to change to the "normal" attributes. All of this avoids having to send a "you are not done here" message when a user clicks a "save" button.

**Comment by esperancaJS** [comment]
kinda done.. still need to handle the disabled logic for invalid forms
