### ISSUE TITLE
Spacing between divisive lines on sidemenu / text attributes

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#17]
The divisive lines on the sidebar have a standart measure between them and the text above/below, here marked by red lines 
- on "Add/remove items" it is on the upper edge of the letters, 
- on "edit the content..." it's on the down edge of the letter which is never just the "d" edge or the "t", "o", etc., but the edge of low hanging letters like "g", "q" or "ç" - I typed them there just to show you

![screen shot 2015-01-27 at 12 06 18](https://cloud.githubusercontent.com/assets/10408369/5917508/9b93d8e4-a61d-11e4-93d4-76a273621b57.png)

This distance is of (guess what) 30px.

Already the distance between the two different text lines is 15px, to keep things mathematical and simple.

Finally, maybe you can use the text styles that I pasted here, all of this is fairly important and balanced out, made to work with all the distances I am giving you.

/\* ADD / REMOVE ITEMS: */
font-family: Montserrat-Light;
font-size: 14px;
color: #FFFFFF;
letter-spacing: 0.85px;
line-height: 32px;

/\* Edit the content of this store's lists: */
font-family: Montserrat-Light;
font-size: 11px;
color: #767075;
line-height: 14px;

**Comment by esperancaJS** [comment]
again.. having guidelines like this is like candy :)
this affected a ton of side page elements, feel free tho check they are the way you want
