### ISSUE TITLE
"EDIT LIST" sidebar

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#20]
Once you click on one of the lists from the previous issue #18 then you end up here:

![edit specific list](https://cloud.githubusercontent.com/assets/10408369/6005636/bc39f58e-ab03-11e4-876f-ec85199fff45.png) ![items in this list](https://cloud.githubusercontent.com/assets/10408369/6005642/d5816392-ab03-11e4-97aa-69a6d492f0f6.jpg)

fair trade, color, popularity, etc etc style:
/\* Fair Trade: */
font-family: Montserrat-Regular;
font-size: 13px;
color: #A59FA3;
line-height: 29px;

------------------------ tabs "in this list" and "add to list":----------------------------------
/\* ACTIVE TAB: _/
font-family: Montserrat-Regular;
font-size: 11px;
color: #F5F5F5;
letter-spacing: 0.72px;
/_ UNACTIVE TAB: */
font-family: Montserrat-Light;
font-size: 11px;
color: #FFFFFF;
letter-spacing: 0.72px;

Little shadow you see under these tabs is the following:
box-shadow: 0px 2px 2px 0px rgba(0,0,0,0.25);

Little orange line of these tabs:
border: 2px solid #E53527;
box-shadow: 0px 2px 2px 0px rgba(0,0,0,0.25);

-------------------------------- items' thumbnails ------------------------------------
Circle with 34px diameter.

/\* Color filter over the image: */
background: rgba(32,29,32,0.50);

This cover filter disappears on hover.

/\* Item's names: */
font-family: Montserrat-Light;
font-size: 13px;
color: #F5F5F5;

/\* Item's data */
font-family: Montserrat-Light;
font-size: 11px;
color: #767075;

Height of each item's space is 50px. Which is also the area marked in grey there.

![screen shot 2015-02-02 at 19 49 25](https://cloud.githubusercontent.com/assets/10408369/6007760/9f8ee870-ab14-11e4-9891-4d509e35fed8.png)

--------------------------- Clicking on the sorter icon -------------------------------

![screen shot 2015-02-03 at 11 08 31](https://cloud.githubusercontent.com/assets/10408369/6019134/1fc7df4e-ab95-11e4-9259-0ecac510b15f.png)

Margins of the text relatively to the box are of 15px;

/\* Rectangle: */
background: #F5F5F5;
box-shadow: 0px 0px 4px 0px rgba(0,0,0,0.70);
border-radius: 1px;

/\* hover bg color: */
background: rgba(215,209,212,0.70);

/\* ALPHABETICALLY: */
font-family: Montserrat-Light;
font-size: 10.9px;
color: #302B2F;
letter-spacing: 0.72px;
line-height: 28px;

-------------------------------- Search behavior ------------------------------------

![screen shot 2015-02-03 at 11 18 11](https://cloud.githubusercontent.com/assets/10408369/6019283/ac9d0dc6-ab96-11e4-88e1-633bcda123f4.png)
![screen shot 2015-02-03 at 11 18 30](https://cloud.githubusercontent.com/assets/10408369/6019284/ae917d9c-ab96-11e4-89b9-48712dcad40f.png)

The augmenting glass icon should become highlighted (w/ red color) on hover and then the Title of the section gives space for a search bar.

/\* Lines: _/
border: 1px solid #E53527;
/_ Ban: */
font-family: Montserrat-Light;
font-size: 13px;
color: #F2F1F1;

**Comment by esperancaJS** [comment]
dooooone! going to sleep :)
