### ISSUE TITLE
ITEMS

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#22]
All Items and Lists' styles are explained on issue #18 

![items](https://cloud.githubusercontent.com/assets/10408369/6020156/794da6a6-aba0-11e4-9b86-455eaa64a475.jpg)
![items by lists](https://cloud.githubusercontent.com/assets/10408369/6020283/f01e3ce0-aba1-11e4-9589-9e3ece87db8b.jpg)
![items in lists](https://cloud.githubusercontent.com/assets/10408369/6020305/4acb1320-aba2-11e4-86be-856c5c3aea90.jpg)

/\* Name of List's background image's shadow: */
box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.25);

**Comment by esperancaJS** [comment]
done :)
