### ISSUE TITLE
Sidebar: interactions visible only on hover

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#3]
(except for dropdown arrows)

**Comment by esperancaJS** [comment]
even interactions relative to the currently open market or store ?

**Comment by mariacovasgrilo** [comment]
Well, I meant stuff like the icons on the right side of the sections:
![screen-shot-2015-01-11-at-12 30](https://cloud.githubusercontent.com/assets/10408369/5695072/eee26746-998d-11e4-8d6d-17b5262cf107.jpg)

But, now that you mention it, I think that all the dropdown menus should be closed on the sidebar, with the subsections of the menus hidden, except, like you said, for the subsections currently relevant for the page you are in, like:
![shop-sidemenu](https://cloud.githubusercontent.com/assets/10408369/5695085/477d3902-998f-11e4-9d9d-3074debe6eec.jpg)
It just seems to me like it goes from absolute "what the hell is going on here on this side bar" to "oh nice, this is where I am, and those are other things"

**Comment by esperancaJS** [comment]
true, it becomes much easier to understand where you are
