### ISSUE TITLE
Incoming Orders Layout

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#35]
![merkatsu_orders_1](https://cloud.githubusercontent.com/assets/10408369/6199742/0b3f6116-b44e-11e4-8ae3-fd53f06077e9.jpg)

/\* Willie Reade etc: */
font-family: Montserrat-Light;
font-size: 13px;
color: #F5F5F5;
line-height: 60px;

/\* Order Info : */
font-family: Montserrat-Light;
font-size: 11px;
color: #767075;
line-height: 60px;

/\* Dividing Lines: */
border: 1px solid #302B2F;
length: 280px;
margin-left: 30px;

City names:
margin-left: 85px;

Shop names:
margin-left: 173px;

Icons:
margin-right: 30px;

/\* active tab text ("pending"): */
font-family: Montserrat-Regular;
font-size: 11px;
color: #F5F5F5;
letter-spacing: 0.72px;

/\* unactive tab text ("all"): */
font-family: Montserrat-Light;
font-size: 11px;
color: #FFFFFF;
letter-spacing: 0.72px;

![screen shot 2015-02-14 at 13 44 58](https://cloud.githubusercontent.com/assets/10408369/6199759/bf9260c2-b44f-11e4-8922-ffbe267c9a43.png)
![screen shot 2015-02-14 at 13 20 54](https://cloud.githubusercontent.com/assets/10408369/6199754/8401856a-b44f-11e4-87df-2c985655618a.png)

Since the order was marked as sent already, the option list is disabled and so are all its elements (as seen above):
icon changes color:
background: #D1CCCF;
the text changes color too:
color: #C4BFC2;

![screen shot 2015-02-14 at 13 22 24](https://cloud.githubusercontent.com/assets/10408369/6199755/8c0cc15c-b44f-11e4-8ec7-4c219eb6486b.png)

Distance between icons and text: 10px;

![screen shot 2015-02-14 at 13 26 51](https://cloud.githubusercontent.com/assets/10408369/6199774/298c83ea-b450-11e4-8e25-2757b9dfb22d.png)

/\* Window: */
background: #F5F5F5;
box-shadow: 0px 0px 8px 2px rgba(0,0,0,0.70);
border-radius: 2px;
width: 294px;
height: 178px;
padding: 20px;

/\* Line: */
border: 1px solid rgba(165,159,162,0.50);

/\* DO IT and CANCEL: */
font-family: Montserrat-Regular;
font-size: 11px;
color: #E53527;
letter-spacing: 0.73px;
margin-top: 20px;

/\* Refuse Order: */
font-family: Montserrat-Light;
font-size: 18px;
color: #E53527;

/\* "Are you sure?" text: */
font-family: Montserrat-Light;
font-size: 13px;
color: #302B2F;
line-height: 19px;
margin-bottom: 30px;
margin-top: 20px;

The "are you sure" text field should have maximum 240px width.

The background should become darker, having a filter like this:
background: rgba(32,28,31,0.80);

**Comment by esperancaJS** [comment]
I was thinking of adding another line with super small circles with images of items. 
This would also help for 'made orders' and 'market orders' where the first line with the creator of the order does not show.
Thoughts ?

**Comment by mariacovasgrilo** [comment]
The images of the items line thing looks great and makes perfect sense, kudos!

The only thing I have to say is, put the lines between orders with the same thickness of the upper line:
![screen shot 2015-04-26 at 22 42 12](https://cloud.githubusercontent.com/assets/10408369/7339414/95caee0a-ec65-11e4-85e8-1690a6bd6435.png)

else, flawless!
