### ISSUE TITLE
Cart hover Layout

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#37]
![screen shot 2015-02-16 at 12 47 41](https://cloud.githubusercontent.com/assets/10408369/6212183/1d130180-b5da-11e4-8613-ea23a372b116.png)

/\* Rectangle: */
background: #F5F5F5;
box-shadow: 0px 0px 6px 0px rgba(0,0,0,0.50);
border-radius: 2px;
height: 562px;
width: 274px;
padding: 30px;

/\* GO TO CART: */
font-family: Montserrat-Regular;
font-size: 11px;
color: #E53527;
letter-spacing: 0.73px;
margin-right: 20px;

/\* Line: */
border: 1px solid rgba(151,151,151,0.50);

/\* 2,13€: */
font-family: Montserrat-Light;
font-size: 11px;
color: #767075;
line-height: 18px;

/\* 1 unit, size L, Fur Colar, etc: */
font-family: Montserrat-Light;
font-size: 11px;
color: #767075;
line-height: 18px;

/\* Red Jacket: */
font-family: Montserrat-Light;
font-size: 13px;
color: #302B2F;

Thumbnail diameter: 34px;
Color filter over the thumbnail image: background: rgba(32,29,32,0.15);

**Comment by esperancaJS** [comment]
love it :D 
But to include also order options we need to separate by store. I can simply exclude order options in this pop up to keep it super simple

**Comment by mariacovasgrilo** [comment]
It can be a good for solution for now but I actually know how I would solve it in the future when it would actually be relevant. But I think it's far from being a priority.

**Comment by esperancaJS** [comment]
agree, I'll just cut out the order options here then ;)

**Comment by mariacovasgrilo** [comment]
Oh and this is the behavior in case of overflow:

![screen shot 2015-02-16 at 14 29 46](https://cloud.githubusercontent.com/assets/10408369/6213504/560345d2-b5e8-11e4-89fd-858a3c474728.png)

The height maintains itself, just add the scrollbar on the side.
