### ISSUE TITLE
Text field / sidebar space / unclutter

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#4]
We had spoken about google's solution to the text field situation with the label over the line at the beginning and then sliding up when you insert your text. It would be a good solution if we didn't have so many text fields that either (one of the two): 1- would have to be waaaay apart from each other or 2- would have to move an entire column of text slightly up or down each time you need to edit text.

Option 1 would not be that bad honestly, but then you'll probably have to scroll down to see all the text fields. Option 2 is shaite.

So my solution was the following (keep in mind that I don't dislike option 1 either):

![spacings](https://cloud.githubusercontent.com/assets/10408369/5627930/272026c6-95a0-11e4-9a52-f0cb55312d35.jpg)

Also, one thing I realize I didn't express well on my designs is that I would like everything closed when you open the sidebar, so you don't have a million things in your face. I believe in that picture I illustrate that better.

I also increased the spacing between each section of the customization, which should apply across the entire platform's sidebar. I am going to try the subtle line separation thing that we had seen together.
...
Ok I don't know about you but I think this makes it soooo much easier to understand what is what in a first glance, it totally organizes and separates everything in a clearer way:

![dividing line experiment](https://cloud.githubusercontent.com/assets/10408369/5628049/ec565c7a-95a1-11e4-88c0-29f40546d9dd.jpg)

I guess this is what we should do then, from this point on, for places like "customize" with several fields to fill in.

**Comment by esperancaJS** [comment]
I liked your solution of increasing spaces and separating with a subtle line, just updated the layouts
