### ISSUE TITLE
emails

### ISSUE THREAD

**Issue by esperancaJS** [merkatsu/website#43]
- email confirmation
- direct message to store/market (admins & sender get cc'd & asked to reply for all)
- market/store admin rights granted
- order made (for buyer & store admins) maybe they get the same email with each other as CC and a suggestion to talk
- order accepted (for buyer & store admins)
- order received
- order rated (for store admins)
- change pass
- pass changed

**Comment by mariacovasgrilo** [comment]
email confirmation: https://us8.admin.mailchimp.com/templates/share?id=30397843_9701c1e65a167d2f03e8_us8
![screen shot 2015-03-14 at 8 45 04 pm](https://cloud.githubusercontent.com/assets/10408369/6653444/1c03582e-ca8b-11e4-991d-9ea0bc3f76eb.png)
