### ISSUE TITLE
Items display move on hover

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#52]
When you are in a page with items, and you hover over the thumbnail of the item, it pops up. 

It shouldn't. It should be static. 

![screen shot 2015-04-05 at 19 03 40](https://cloud.githubusercontent.com/assets/10408369/6997916/90616494-dbc6-11e4-9475-7c8805199776.png)

**Comment by esperancaJS** [comment]
don't you think we should have some kind of animation ?
I used this one because it's the same we use in buttons already

**Comment by mariacovasgrilo** [comment]
The items are not buttons, they are cards. They have a more informative function than a transitional one, therefore I think animations are just distracting and overwhelming in this situation. 

Go through any web commerce page and you'll not see this happening because else when you'd just move the mouse around the page and there would be stuff popping out everywhere.

**Comment by esperancaJS** [comment]
ok makes sense
