### ISSUE TITLE
Sidebar pushes the page to the left

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#55]
When you open the sidebar, the whole page is pushed to the left.

Instead, it should open over the content ("above" it). Illustrated underneath:

![shop](https://cloud.githubusercontent.com/assets/10408369/6997938/d14e3c42-dbc7-11e4-9965-610886832726.png)

**Comment by esperancaJS** [comment]
As we had talked before like this it allowes the user editing to fully see the page.
Why should it be like this?

**Comment by mariacovasgrilo** [comment]
It's true we talked about this before, I seem to have forgotten. But independently of being previously discussed or not, I now felt that this creates some problems with, for example, previewing the look that the page would have. The proportions look completely different. And the stuff on the right side, come to think about it, are not that relevant. For now, I think the best solution for this change of proportions right now would be to just overlay the sidebar, of course not excluding the possibility of creating a different, better solution in the future.

**Comment by esperancaJS** [comment]
some points towards a side page without overlay:
- the main page should look good with any screen size
- overlaying an object that is being edited is confusing
- we could latter implement a feature where the side page expands simulating different screen sizes on the main page
- squarespace does it like this

**Comment by mariacovasgrilo** [comment]
Ok, very good point. I will then have to work on the flexibility of the page, because the way it is right now, is not working. 

What I was saying is that meanwhile, whilst I don't have a solution - because maybe it's not the biggest priority - we should just overlay it, with the conscience that it isn't at all a permanent solution.

**Comment by esperancaJS** [comment]
If after alpha we still feel like it's not working I'll implement a new solution. 
But this should be strongly avoided in my opinion because it's a costly temporary fix that also stears the UX in a different direction

**Comment by djtanuzzo** [comment]
This was labeled as ready yet the sidebar still pushes the content of the page out of screen.

**Comment by esperancaJS** [comment]
yes, because this is a discussion.
And with the new updates I think it is now more clear that this solution is the best

**Comment by djtanuzzo** [comment]
I think this is actually an issue only sometimes, and not always. For some reason sometimes the system clips the content out of screens, and other times it does not. Pics to demonstrate.

![mrkts11](https://cloud.githubusercontent.com/assets/10848233/7234757/3a328a50-e781-11e4-8041-74eb0654a916.png)
![mrkts12](https://cloud.githubusercontent.com/assets/10848233/7234758/3b03de98-e781-11e4-92e5-1f13ea377bb6.png)

**Comment by esperancaJS** [comment]
yep, that's clearly a bug.

skeptic webdevelopment 101: everything done will produce some unexpected behaviors that need atention

for this reason I think we should stick with this kind of side page behaviour and work towards making it work.
