### ISSUE TITLE
Menu and cart don't disappear from header when sidebar opens.

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#56]
Menu and cart don't disappear from header when sidebar opens.

Instead, they should integrate the sidebar, like the example underneath:

![screen shot 2015-04-05 at 19 15 09](https://cloud.githubusercontent.com/assets/10408369/6997943/1af1cd1e-dbc8-11e4-9e6f-3efeaf6197ec.png)

**Comment by esperancaJS** [comment]
duplicate of #1

**Comment by djtanuzzo** [comment]
Not sure if the current iteration can be considered a solution or ready. @mariacovasgrilo should check it out.

![mrkts7](https://cloud.githubusercontent.com/assets/10848233/7234108/bb10515c-e77c-11e4-94f5-9237b3c69dc6.png)
