### ISSUE TITLE
No "order by" on menu editor

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#59]
When editing a menu, there should be a way to order the different menu items.

This could be solved with the same system created for other previous situations:

![screen shot 2015-04-05 at 19 45 17](https://cloud.githubusercontent.com/assets/10408369/6998070/52dc7194-dbcc-11e4-84d8-166495485ed1.png)

**Comment by esperancaJS** [comment]
But this sould also change the menu order for the buyers, do you really think this makes sense?

**Comment by djtanuzzo** [comment]
Whilst I think that having a way to automatically order the items would definitely help, it would actually be even more useful if the user could manually change the order of the items.

Overall I would recommend having a look at how wordpress does the creator interface for making menus, as it is very simple and intuitive, whilst still allowing for a lot of freedom.

**Comment by esperancaJS** [comment]
It is already possible to change the order. You can drag the items to their desired position.

**Comment by mariacovasgrilo** [comment]
oh cool, that was not understandable, so I'll have to find a way to show this better. I'll assign this to myself then.
