### ISSUE TITLE
"back" with browser goes back only on main page, not on sidebar

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#65]
When clicking "back" on browser, it should go back to the exact previous state. So if the main page is on A and I transition it to B and later I make the sidebar go from C to D, when I click the "back" button on the browser, it should present the mainpage on B and the sidebar on C. Basically, it should just move one step back on the whole combination.

I understand this is super confusing but you can ask me more about it if necessary. I couldn't come up with a better way to explain :x

**Comment by esperancaJS** [comment]
I understand what you sugest.
I have plans to in the future incorporate side page navigation into the main page navigation.
But I think that since this might require a great deal of restructuring we should focus on the 'buyer' navigation for now.
