### ISSUE TITLE
"save" button is only on top of the sidebar

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#67]
After a long list of definitions and textfields, it's cool if you don't have to scroll all the way back up to click "save". 

It would be good to have the same two buttons on the bottom of the sidebar (back and save, exactly the way they are up, but down too)

**Comment by djtanuzzo** [comment]
On chrome I see that the "back" and "save" button are following you around, however they are clipping just out of visibility.

![mrkts8](https://cloud.githubusercontent.com/assets/10848233/8253405/679d93f6-1687-11e5-9450-a0446b98f9a7.png)
