### ISSUE TITLE
Cart: when clicking on item name or thumbnail, no item page shows up

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#69]
The user should be allowed to open the item page when clicking on the thumbnail or name of product.

It shouldn't open the "edit" item page, but a clean item page, with no pre-selected item options.

**Comment by PedroEsperanca** [comment]
so an item modal where he can add a 'fresh' new item to the cart if he wants, right ?

**Comment by esperancaJS** [comment]
done, I marked as ready for review to be sure that you think it's as intuitive as it can be
