### ISSUE TITLE
"save" should turn orange when it can be used

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#7]
Meaning, when I can't save (because info is missing, or whatever) it's grey. When it's saveable, it turns orange.
![screen shot 2015-01-20 at 13 50 45](https://cloud.githubusercontent.com/assets/10408369/5817379/91ccb424-a0ab-11e4-82a7-b10d25442a30.png)

**Comment by esperancaJS** [comment]
aaaah! good idea

**Comment by mariacovasgrilo** [comment]
That was the original idea all along, but obviously I didn't explain it right :p also, caps lock on all buttons.

And a round corner with a radius of 1px in the button shape. I understand it was a really small detail for you to be able to notice it, but it does make a difference in the overall look.
