### ISSUE TITLE
Cart: items are not being grouped

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#70]
When ordering same exact items with same exact item options selected, they should be grouped in the cart, instead of divided.

![screen shot 2015-04-05 at 20 41 40](https://cloud.githubusercontent.com/assets/10408369/6998311/3ff2e5ce-dbd4-11e4-907b-7f642f8ac5e0.png)

**Comment by esperancaJS** [comment]
This is supposed to happen, otherwise it would be impossible to order the same item with diferent buyer options
