### ISSUE TITLE
Cart: textfields are in orange

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#72]
The textfields in the cart are not to be in orange.

Follow instructions on issue #38 please.

![screen shot 2015-04-05 at 20 47 29](https://cloud.githubusercontent.com/assets/10408369/6998325/1ba444c8-dbd5-11e4-9dc0-f62fd1adf7e9.png)

**Comment by esperancaJS** [comment]
The orange is used all over the platform to indicate that an input is still required. 
Also how did you like the solution for the lable to go underneath so that the user still knows what the input is

**Comment by mariacovasgrilo** [comment]
I like that, I think it's a nice solution. I actually came across a place that has a bunch of cool textfield solutions. My only problem with this one is that it would end up occupying more vertical space and sometimes it becomes a problem with distances. But I will try and correct that with my next design and then I'll make an issue just about that.

about having orange as a marker of stuff missing, I feel like it might just become overwhelming, so maybe there's a better way to mark that. once I think about it I'll also make an issue on that.

**Comment by esperancaJS** [comment]
ok so I'll assign this one to you until you find a better solution
