### ISSUE TITLE
Items > edit items not possible to delete item directly on the list of items

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#74]
It should be possible to delete several items, instead of having to do that one by one in their individual pages.

It should be possible to do it so here: (having a little trashcan showing up in front of it)
![screen shot 2015-04-05 at 20 58 49](https://cloud.githubusercontent.com/assets/10408369/6998342/9a8fc644-dbd6-11e4-9207-2da6b108dfd8.png)

**Comment by esperancaJS** [comment]
So I should just add a trash can there? 
I think that items should not be delectable here since it gives the idea that they are easily discardable, and thus not important. 
If we do add this trashcans in front of items we should do this to pages and lists also?

**Comment by djtanuzzo** [comment]
Yes, I would add a trashcan on the right, and generally would replace a lot of spaces where there is an X to delete something with a trashcan for clarity.

**Comment by esperancaJS** [comment]
I feel that these items should not be deleted so easily, that is the whole point of the math before deleting. 
What if we open a pop up when clicking on the trashcan with the math?

**Comment by mariacovasgrilo** [comment]
I feel like we should discuss this further, but yeah, I was thinking of something like that. The problem would be when you want to delete several ones in a row. In that case we should maybe have a checkbox system with a trashcan on top, and then the math would pop up.
