### ISSUE TITLE
Items cannot be directly edited when opening them in the store

### ISSUE THREAD

**Issue by djtanuzzo** [merkatsu/website#86]
Right now it is not possible to directly edit an item by opening it in the store. For example I was checking out my store orders in the sidebar and then started browsing the store. I opened the item and wanted to edit its price, however it did not open on the sidebar.

![mrkts4](https://cloud.githubusercontent.com/assets/10848233/7117051/2d6c7396-e1ee-11e4-8d04-e6882a27cf36.png)

It would be good if there was a button to edit the item when you are on it. If it was to automatically switch to the edit item tab whilst you were doing something that still needed to be saved, then it could lead to a frustrating experience.

**Comment by esperancaJS** [comment]
There is a limit to how much you can simplify the user experience while still maintain the UI simple.
I'm afraid this might me one of them.

One thing the user could do to edit the item without having to close his open side page:
- open the link in a new tab
- click on edit item in the main side page

**Comment by djtanuzzo** [comment]
Is there no way to add an "edit item" button that takes you directly to the "edit item" tab?

It would basically mean that I don't have to close my tabs, go to the store tab, then click the items tab, then look for the item, and then finally click on it.

**Comment by esperancaJS** [comment]
when an item is open you have an edit item button in the main menu, under the open store/market name

**Comment by djtanuzzo** [comment]
What I am asking is, would it not be possible to have a button on the item that automatically opens the "edit item" tab in the sidebar? Maybe just put it on the top right like in pic related? (though maria would have to give the final design blessing on it)

![mrkts6](https://cloud.githubusercontent.com/assets/10848233/7117632/f00f4d62-e1f1-11e4-9900-f33541f64419.png)

**Comment by esperancaJS** [comment]
Maybe it does make sense to have this button somewhere.
But if we have it for the item we need to have it for stores, markets, collections and pages also for the sake of consistency. For this reason I have thought of putting on the bar between the cart and menu button.
We need @mariacovasgrilo  opinion.

But I would rather leave it clear for the users that all admin buttons and inputs are on the side page. 
It sucks to force the users to have to learn new things, but with this one lesson the platform becomes a lot simpler.
