### ISSUE TITLE
Username instead of "tests"

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#9]
I know this is something fast and silly, but I guess it's still necessary to change so.
![screen shot 2015-01-21 at 14 29 39](https://cloud.githubusercontent.com/assets/10408369/5836817/09b08762-a17a-11e4-9e01-370ad16af7c1.png)

**Comment by esperancaJS** [comment]
the username in this case IS <b>tests</b> :p you can change it in Settings
