### ISSUE TITLE
Creating new item looks confusing due to missing image

### ISSUE THREAD

**Issue by djtanuzzo** [merkatsu/website#92]
When you create a new item the preview on the left looks confusing and not understandable.

![mrkts3](https://cloud.githubusercontent.com/assets/10848233/7181312/98bda6e2-e441-11e4-9468-0ecacac49bd7.png)

I suggest having a placeholder image, which gives the user a better idea of how things will look like. Here is an example of what it could looks like:

![mrkts4](https://cloud.githubusercontent.com/assets/10848233/7181353/041a5872-e442-11e4-811f-8cb1cd842246.png)

Here is the placeholder image I used:

![placeholder](https://cloud.githubusercontent.com/assets/10848233/7181357/0dcac1ea-e442-11e4-8a32-714061ed6a32.jpg)

**Comment by PedroEsperanca** [comment]
Maybe we could get an image more friendly with flat design, but yes I'll fix this for sure
