### ISSUE TITLE
Creating new item form badly arranged

### ISSUE THREAD

**Issue by djtanuzzo** [merkatsu/website#93]
When creating a new item the form is arranged in such a way that can create confusion, as such I propose moving the following items:
- About should be placed right below Description, and above Images
- Cost and Availability should be combined (if possible, see image)

Additionally the text "to which store collections" should be re-named to "Select which collections this item belongs to:"

![mrkts6](https://cloud.githubusercontent.com/assets/10848233/7206539/6fffabf8-e52a-11e4-803c-f91a627bcdb2.png)

**Comment by esperancaJS** [comment]
good idea!
