### ISSUE TITLE
Scroll bar is not reachable and instead highlights text

### ISSUE THREAD

**Issue by djtanuzzo** [merkatsu/website#97]
When trying to move the scroll bar by clicking and dragging at its topmost position, it highlights the language, cart and menu text instead. This makes it impossible to pull the scroll bar.

![mrkts8](https://cloud.githubusercontent.com/assets/10848233/7234364/8c1ca24a-e77e-11e4-9dd9-f975329a4b37.png)

**Comment by esperancaJS** [comment]
lol I wouldn't call this one fatal.. It's a small UX bug, anyway, it's fixed
