### ISSUE TITLE
Changing the price range slider to a number below 100 is impossible and clips out of screen

### ISSUE THREAD

**Issue by djtanuzzo** [merkatsu/website#99]
For some reason I am not able to set the price range slider to a number below 100 that is not 10 or 1, and when I do then the slider clips out of screen.

![mrkts9](https://cloud.githubusercontent.com/assets/10848233/7234567/ea33fd50-e77f-11e4-8058-3382d5ce9393.png)

**Comment by esperancaJS** [comment]
super weird, tested this on all browsers on my PC (windows 8) and I had no issues.
What OS do you have ? also, does it also happen in other browsers besides FF? If so it's a bug with some plugin you have

**Comment by esperancaJS** [comment]
ah never mind, found it
